import "./globals.css";
import Header from "./shared/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['400', '500', '700', '900'], // Update weights to available options
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
